FROM python:3.13

# Uygulama dizinini oluştur
RUN mkdir /app
WORKDIR /app

# Ortam değişkenlerini ayarla
ENV PYTHONPATH=/app

# Pythonun .pyc dosyalarını oluşturmasını engelle

ENV PYTHONDONTWRITEBYTECODE=1
# Pythonun çıktıyı önbelleğe almadan anında yazmasını sağlar
ENV PYTHONUNBUFFERED=1

# pip'i güncelle
RUN pip install --upgrade pip

# Gereksinim dosyasını kopyala ve bağımlılıkları yükle
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Django projesini kopyala
COPY . .

# Django portunu dışa aç
EXPOSE 8000

# Entrypoint betiğini kopyala ve çalıştırılabilir yap
COPY entrypoint.sh .
RUN chmod +x ./entrypoint.sh

# Entrypoint komutunu ayarla
ENTRYPOINT ["./entrypoint.sh"]
